### ISSUE TITLE
Files architecture: Create dedicated folders and submodules files

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-mapchooser-extended#17]
With upcoming changes MCE will be around 4k lines... So it will be easier to maintain. 
2 main plugins will have their own folders (mapchooser_extended, nominations_extended)
For submodules in each folder, I was thinking to something like:
- [ ] Convars
- [ ] Native
- [ ] Forwards
- [ ] Menus
- [ ] Commands
- [ ] Events
- [ ] Core

cc @maxime1907

**Comment by maxime1907** [comment]
also the best thing would be to split each plugin into their own repos:
- https://github.com/srcdslab/sm-plugin-mapchooser-extended
- https://github.com/srcdslab/sm-plugin-mapchooser-extended-sounds
- https://github.com/srcdslab/sm-plugin-nominations-extended
- https://github.com/srcdslab/sm-plugin-rockthevote-extended

**Comment by maxime1907** [comment]
oh okay so these plugins are way too much glued together then we can keep it like that
