### ISSUE TITLE
bug: Player reconnection corrupts map nomination attribution

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-mapchooser-extended#29]
### Description:
When a player disconnects and a new player joins with the same client index, the nomination system incorrectly attributes map nominations to the new player instead of maintaining the original nominator's information.
### Impact:
- Displays wrong nominator names in map voting system
- Creates confusion about who actually nominated specific maps
- Affects nomination history accuracy

### Possible solution:
- Create an Internal function to return who nominated the map based on map name instead of the current system
- Native call for it
- Use only one buffer (more memory efficient)

**Comment by maxime1907** [comment]
i think it would be easier to just remove the nomination when player disconnects

**Comment by Rushaway** [comment]
It was already the case but leading to some wrong infos displayed sometimes, the change in [de297ae](https://github.com/Rushaway/sm-plugin-mapchooser-extended/commit/de297ae2f7e0e76485501b49df1c37a6567a79fc) include API support, and also use less memory.

**Comment by maxime1907** [comment]
why sometimes?

**Comment by maxime1907** [comment]
i mean it should be straightforward like:
1. player disconnect = remove all nomination info
2. player connects with fresh values that are set to default ones (empty)

**Comment by Rushaway** [comment]
It was already the case in `NominationsOnClientDisconnect` 
But I still think #30 is more logic and easier to maintain (+memory improvement)

Old mehtod: 
```
- Size = (MAXPLAYERS + 1) * PLATFORM_MAX_PATH
- Size = 65 * 256
- Total = 16,640 bytes (16.25 KB)
```

New:
```
- Map name: 64 chars
- Separator ":": 1 char
- Player name: 32 chars
- Entry separator ";": 1 char
Total per entry = 64 + 1 + 32 + 1 = 98 chars

For 9 players:
98 chars * 9 entries = 882 chars

Add safety margin for null terminator and potential UTF-8 characters:
Round up to 1024 chars (1 KB)
```

**Comment by maxime1907** [comment]
memory is not a problem since its really small buffers

**Comment by Rushaway** [comment]
I think that should solve the issue (Untested)

**Comment by maxime1907** [comment]
Nice its better that way
